
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2021.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xeucdis.h"

/*
* The configuration table for devices
*/

XEucdis_Config XEucdis_ConfigTable[XPAR_XEUCDIS_NUM_INSTANCES] =
{
	{
		XPAR_EUCDIS_0_DEVICE_ID,
		XPAR_EUCDIS_0_S_AXI_CONTROL_BASEADDR
	}
};


