// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module eucDis_sqrt_fixed_27_27_s (
        ap_clk,
        ap_rst,
        x,
        ap_return
);


input   ap_clk;
input   ap_rst;
input  [25:0] x;
output  [13:0] ap_return;

wire   [29:0] x_l_I_V_26_fu_310_p3;
reg   [29:0] x_l_I_V_26_reg_1209;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_pp0_stage0_11001;
wire   [13:0] res_I_V_25_fu_318_p3;
reg   [13:0] res_I_V_25_reg_1215;
wire   [0:0] icmp_ln489_2_fu_358_p2;
reg   [0:0] icmp_ln489_2_reg_1221;
wire   [5:0] sub_ln258_1_fu_364_p2;
reg   [5:0] sub_ln258_1_reg_1227;
wire   [29:0] x_l_I_V_29_fu_549_p3;
reg   [29:0] x_l_I_V_29_reg_1232;
wire   [13:0] res_I_V_28_fu_557_p3;
reg   [13:0] res_I_V_28_reg_1238;
reg   [6:0] p_Result_12_reg_1244;
reg   [8:0] p_Result_13_reg_1249;
wire   [29:0] x_l_I_V_30_fu_706_p3;
reg   [29:0] x_l_I_V_30_reg_1255;
wire   [13:0] res_I_V_fu_714_p3;
reg   [13:0] res_I_V_reg_1261;
wire   [0:0] icmp_ln489_7_fu_754_p2;
reg   [0:0] icmp_ln489_7_reg_1267;
wire   [10:0] sub_ln258_6_fu_760_p2;
reg   [10:0] sub_ln258_6_reg_1273;
wire   [29:0] x_l_I_V_32_fu_863_p3;
reg   [29:0] x_l_I_V_32_reg_1278;
wire   [13:0] res_I_V_31_fu_871_p3;
reg   [13:0] res_I_V_31_reg_1284;
wire   [0:0] icmp_ln489_9_fu_911_p2;
reg   [0:0] icmp_ln489_9_reg_1290;
wire   [12:0] sub_ln258_8_fu_917_p2;
reg   [12:0] sub_ln258_8_reg_1296;
wire   [29:0] x_l_I_V_34_fu_1020_p3;
reg   [29:0] x_l_I_V_34_reg_1301;
wire   [13:0] res_I_V_33_fu_1028_p3;
reg   [13:0] res_I_V_33_reg_1307;
wire   [0:0] icmp_ln489_11_fu_1068_p2;
reg   [0:0] icmp_ln489_11_reg_1313;
wire   [14:0] sub_ln258_10_fu_1074_p2;
reg   [14:0] sub_ln258_10_reg_1319;
wire    ap_block_pp0_stage0;
wire   [1:0] tmp_fu_188_p4;
wire   [2:0] zext_ln489_12_fu_198_p1;
wire   [2:0] add_ln258_fu_208_p2;
wire   [29:0] zext_ln712_fu_184_p1;
wire  signed [3:0] sext_ln323_fu_214_p1;
wire   [0:0] icmp_ln489_fu_202_p2;
wire   [29:0] p_Result_38_fu_218_p5;
wire   [1:0] select_ln489_fu_246_p3;
wire   [29:0] x_l_I_V_25_fu_230_p3;
wire   [2:0] tmp_2_fu_254_p3;
wire   [4:0] p_Result_5_fu_262_p4;
wire   [4:0] zext_ln489_fu_272_p1;
wire   [4:0] sub_ln258_fu_282_p2;
wire   [13:0] select_ln239_fu_238_p3;
wire   [0:0] icmp_ln489_1_fu_276_p2;
wire   [29:0] p_Result_39_fu_288_p5;
wire   [13:0] p_Result_40_fu_300_p4;
wire   [3:0] p_Result_8_fu_326_p4;
wire   [4:0] tmp_3_fu_336_p3;
wire   [5:0] p_Result_9_fu_344_p4;
wire   [5:0] zext_ln489_1_fu_354_p1;
wire   [29:0] p_Result_41_fu_370_p5;
wire   [13:0] p_Result_42_fu_380_p4;
wire   [13:0] res_I_V_26_fu_395_p3;
wire   [4:0] p_Result_s_fu_401_p4;
wire   [29:0] x_l_I_V_27_fu_389_p3;
wire   [5:0] tmp_4_fu_411_p3;
wire   [6:0] p_Result_1_fu_419_p4;
wire   [6:0] zext_ln489_2_fu_429_p1;
wire   [6:0] sub_ln258_2_fu_439_p2;
wire   [0:0] icmp_ln489_3_fu_433_p2;
wire   [29:0] p_Result_43_fu_445_p5;
wire   [13:0] p_Result_44_fu_457_p4;
wire   [13:0] res_I_V_27_fu_475_p3;
wire   [5:0] p_Result_6_fu_483_p4;
wire   [29:0] x_l_I_V_28_fu_467_p3;
wire   [6:0] tmp_5_fu_493_p3;
wire   [7:0] p_Result_7_fu_501_p4;
wire   [7:0] zext_ln489_3_fu_511_p1;
wire   [7:0] sub_ln258_3_fu_521_p2;
wire   [0:0] icmp_ln489_4_fu_515_p2;
wire   [29:0] p_Result_45_fu_527_p5;
wire   [13:0] p_Result_46_fu_539_p4;
wire   [7:0] tmp_6_fu_585_p3;
wire   [8:0] zext_ln489_4_fu_592_p1;
wire   [8:0] sub_ln258_4_fu_601_p2;
wire   [0:0] icmp_ln489_5_fu_596_p2;
wire   [29:0] p_Result_47_fu_606_p5;
wire   [13:0] p_Result_48_fu_617_p4;
wire   [13:0] res_I_V_29_fu_633_p3;
wire   [7:0] p_Result_15_fu_640_p4;
wire   [29:0] x_l_I_V_fu_626_p3;
wire   [8:0] tmp_7_fu_650_p3;
wire   [9:0] p_Result_16_fu_658_p4;
wire   [9:0] zext_ln489_5_fu_668_p1;
wire   [9:0] sub_ln258_5_fu_678_p2;
wire   [0:0] icmp_ln489_6_fu_672_p2;
wire   [29:0] p_Result_49_fu_684_p5;
wire   [13:0] p_Result_50_fu_696_p4;
wire   [8:0] p_Result_18_fu_722_p4;
wire   [9:0] tmp_8_fu_732_p3;
wire   [10:0] p_Result_19_fu_740_p4;
wire   [10:0] zext_ln489_6_fu_750_p1;
wire   [29:0] p_Result_51_fu_766_p5;
wire   [13:0] p_Result_52_fu_776_p4;
wire   [13:0] res_I_V_30_fu_791_p3;
wire   [9:0] p_Result_21_fu_797_p4;
wire   [29:0] x_l_I_V_31_fu_785_p3;
wire   [10:0] tmp_9_fu_807_p3;
wire   [11:0] p_Result_22_fu_815_p4;
wire   [11:0] zext_ln489_7_fu_825_p1;
wire   [11:0] sub_ln258_7_fu_835_p2;
wire   [0:0] icmp_ln489_8_fu_829_p2;
wire   [29:0] p_Result_53_fu_841_p5;
wire   [13:0] p_Result_54_fu_853_p4;
wire   [10:0] p_Result_24_fu_879_p4;
wire   [11:0] tmp_s_fu_889_p3;
wire   [12:0] p_Result_25_fu_897_p4;
wire   [12:0] zext_ln489_8_fu_907_p1;
wire   [29:0] p_Result_55_fu_923_p5;
wire   [13:0] p_Result_56_fu_933_p4;
wire   [13:0] res_I_V_32_fu_948_p3;
wire   [11:0] p_Result_27_fu_954_p4;
wire   [29:0] x_l_I_V_33_fu_942_p3;
wire   [12:0] tmp_1_fu_964_p3;
wire   [13:0] p_Result_28_fu_972_p4;
wire   [13:0] zext_ln489_9_fu_982_p1;
wire   [13:0] sub_ln258_9_fu_992_p2;
wire   [0:0] icmp_ln489_10_fu_986_p2;
wire   [29:0] p_Result_57_fu_998_p5;
wire   [13:0] p_Result_58_fu_1010_p4;
wire   [12:0] p_Result_30_fu_1036_p4;
wire   [13:0] tmp_10_fu_1046_p3;
wire   [14:0] p_Result_31_fu_1054_p4;
wire   [14:0] zext_ln489_10_fu_1064_p1;
wire   [29:0] p_Result_59_fu_1080_p5;
wire   [13:0] p_Result_60_fu_1090_p4;
wire   [13:0] res_I_V_34_fu_1105_p3;
wire   [29:0] x_l_I_V_35_fu_1099_p3;
wire   [14:0] tmp_11_fu_1111_p3;
wire   [15:0] trunc_ln640_fu_1119_p1;
wire   [15:0] zext_ln489_11_fu_1123_p1;
wire   [15:0] sub_ln258_11_fu_1133_p2;
wire   [0:0] icmp_ln489_12_fu_1127_p2;
wire   [29:0] p_Result_61_fu_1139_p5;
wire   [13:0] p_Result_62_fu_1151_p4;
wire   [13:0] res_I_V_35_fu_1169_p3;
wire   [27:0] mul_I_V_fu_1177_p3;
wire   [29:0] x_l_I_V_36_fu_1161_p3;
wire   [29:0] zext_ln717_fu_1185_p1;
wire   [0:0] p_Result_s_53_fu_1189_p2;
wire   [13:0] res_I_V_23_fu_1195_p2;
reg   [25:0] x_int_reg;
wire    ap_ce_reg;

always @ (posedge ap_clk) begin
    x_int_reg <= x;
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln489_11_reg_1313 <= icmp_ln489_11_fu_1068_p2;
        icmp_ln489_2_reg_1221 <= icmp_ln489_2_fu_358_p2;
        icmp_ln489_7_reg_1267 <= icmp_ln489_7_fu_754_p2;
        icmp_ln489_9_reg_1290 <= icmp_ln489_9_fu_911_p2;
        p_Result_12_reg_1244 <= {{res_I_V_28_fu_557_p3[13:7]}};
        p_Result_13_reg_1249 <= {{x_l_I_V_29_fu_549_p3[22:14]}};
        res_I_V_25_reg_1215 <= res_I_V_25_fu_318_p3;
        res_I_V_28_reg_1238 <= res_I_V_28_fu_557_p3;
        res_I_V_31_reg_1284 <= res_I_V_31_fu_871_p3;
        res_I_V_33_reg_1307 <= res_I_V_33_fu_1028_p3;
        res_I_V_reg_1261 <= res_I_V_fu_714_p3;
        sub_ln258_10_reg_1319 <= sub_ln258_10_fu_1074_p2;
        sub_ln258_1_reg_1227 <= sub_ln258_1_fu_364_p2;
        sub_ln258_6_reg_1273 <= sub_ln258_6_fu_760_p2;
        sub_ln258_8_reg_1296 <= sub_ln258_8_fu_917_p2;
        x_l_I_V_26_reg_1209 <= x_l_I_V_26_fu_310_p3;
        x_l_I_V_29_reg_1232 <= x_l_I_V_29_fu_549_p3;
        x_l_I_V_30_reg_1255 <= x_l_I_V_30_fu_706_p3;
        x_l_I_V_32_reg_1278 <= x_l_I_V_32_fu_863_p3;
        x_l_I_V_34_reg_1301 <= x_l_I_V_34_fu_1020_p3;
    end
end

assign add_ln258_fu_208_p2 = ($signed(zext_ln489_12_fu_198_p1) + $signed(3'd7));

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_return = ((p_Result_s_53_fu_1189_p2[0:0] == 1'b1) ? res_I_V_23_fu_1195_p2 : res_I_V_35_fu_1169_p3);

assign icmp_ln489_10_fu_986_p2 = ((p_Result_28_fu_972_p4 < zext_ln489_9_fu_982_p1) ? 1'b1 : 1'b0);

assign icmp_ln489_11_fu_1068_p2 = ((p_Result_31_fu_1054_p4 < zext_ln489_10_fu_1064_p1) ? 1'b1 : 1'b0);

assign icmp_ln489_12_fu_1127_p2 = ((trunc_ln640_fu_1119_p1 < zext_ln489_11_fu_1123_p1) ? 1'b1 : 1'b0);

assign icmp_ln489_1_fu_276_p2 = ((p_Result_5_fu_262_p4 < zext_ln489_fu_272_p1) ? 1'b1 : 1'b0);

assign icmp_ln489_2_fu_358_p2 = ((p_Result_9_fu_344_p4 < zext_ln489_1_fu_354_p1) ? 1'b1 : 1'b0);

assign icmp_ln489_3_fu_433_p2 = ((p_Result_1_fu_419_p4 < zext_ln489_2_fu_429_p1) ? 1'b1 : 1'b0);

assign icmp_ln489_4_fu_515_p2 = ((p_Result_7_fu_501_p4 < zext_ln489_3_fu_511_p1) ? 1'b1 : 1'b0);

assign icmp_ln489_5_fu_596_p2 = ((p_Result_13_reg_1249 < zext_ln489_4_fu_592_p1) ? 1'b1 : 1'b0);

assign icmp_ln489_6_fu_672_p2 = ((p_Result_16_fu_658_p4 < zext_ln489_5_fu_668_p1) ? 1'b1 : 1'b0);

assign icmp_ln489_7_fu_754_p2 = ((p_Result_19_fu_740_p4 < zext_ln489_6_fu_750_p1) ? 1'b1 : 1'b0);

assign icmp_ln489_8_fu_829_p2 = ((p_Result_22_fu_815_p4 < zext_ln489_7_fu_825_p1) ? 1'b1 : 1'b0);

assign icmp_ln489_9_fu_911_p2 = ((p_Result_25_fu_897_p4 < zext_ln489_8_fu_907_p1) ? 1'b1 : 1'b0);

assign icmp_ln489_fu_202_p2 = ((tmp_fu_188_p4 == 2'd0) ? 1'b1 : 1'b0);

assign mul_I_V_fu_1177_p3 = {{14'd0}, {res_I_V_35_fu_1169_p3}};

assign p_Result_15_fu_640_p4 = {{res_I_V_29_fu_633_p3[13:6]}};

assign p_Result_16_fu_658_p4 = {{x_l_I_V_fu_626_p3[21:12]}};

assign p_Result_18_fu_722_p4 = {{res_I_V_fu_714_p3[13:5]}};

assign p_Result_19_fu_740_p4 = {{x_l_I_V_30_fu_706_p3[20:10]}};

assign p_Result_1_fu_419_p4 = {{x_l_I_V_27_fu_389_p3[24:18]}};

assign p_Result_21_fu_797_p4 = {{res_I_V_30_fu_791_p3[13:4]}};

assign p_Result_22_fu_815_p4 = {{x_l_I_V_31_fu_785_p3[19:8]}};

assign p_Result_24_fu_879_p4 = {{res_I_V_31_fu_871_p3[13:3]}};

assign p_Result_25_fu_897_p4 = {{x_l_I_V_32_fu_863_p3[18:6]}};

assign p_Result_27_fu_954_p4 = {{res_I_V_32_fu_948_p3[13:2]}};

assign p_Result_28_fu_972_p4 = {{x_l_I_V_33_fu_942_p3[17:4]}};

assign p_Result_30_fu_1036_p4 = {{res_I_V_33_fu_1028_p3[13:1]}};

assign p_Result_31_fu_1054_p4 = {{x_l_I_V_34_fu_1020_p3[16:2]}};

assign p_Result_38_fu_218_p5 = {{zext_ln712_fu_184_p1[29:28]}, {sext_ln323_fu_214_p1}, {zext_ln712_fu_184_p1[23:0]}};

assign p_Result_39_fu_288_p5 = {{x_l_I_V_25_fu_230_p3[29:27]}, {sub_ln258_fu_282_p2}, {x_l_I_V_25_fu_230_p3[21:0]}};

assign p_Result_40_fu_300_p4 = {select_ln239_fu_238_p3[14 - 1:12], |(1'd1), select_ln239_fu_238_p3[10:0]};

assign p_Result_41_fu_370_p5 = {{x_l_I_V_26_reg_1209[29:26]}, {sub_ln258_1_reg_1227}, {x_l_I_V_26_reg_1209[19:0]}};

assign p_Result_42_fu_380_p4 = {res_I_V_25_reg_1215[14 - 1:11], |(1'd1), res_I_V_25_reg_1215[9:0]};

assign p_Result_43_fu_445_p5 = {{x_l_I_V_27_fu_389_p3[29:25]}, {sub_ln258_2_fu_439_p2}, {x_l_I_V_27_fu_389_p3[17:0]}};

assign p_Result_44_fu_457_p4 = {res_I_V_26_fu_395_p3[14 - 1:10], |(1'd1), res_I_V_26_fu_395_p3[8:0]};

assign p_Result_45_fu_527_p5 = {{x_l_I_V_28_fu_467_p3[29:24]}, {sub_ln258_3_fu_521_p2}, {x_l_I_V_28_fu_467_p3[15:0]}};

assign p_Result_46_fu_539_p4 = {res_I_V_27_fu_475_p3[14 - 1:9], |(1'd1), res_I_V_27_fu_475_p3[7:0]};

assign p_Result_47_fu_606_p5 = {{x_l_I_V_29_reg_1232[29:23]}, {sub_ln258_4_fu_601_p2}, {x_l_I_V_29_reg_1232[13:0]}};

assign p_Result_48_fu_617_p4 = {res_I_V_28_reg_1238[14 - 1:8], |(1'd1), res_I_V_28_reg_1238[6:0]};

assign p_Result_49_fu_684_p5 = {{x_l_I_V_fu_626_p3[29:22]}, {sub_ln258_5_fu_678_p2}, {x_l_I_V_fu_626_p3[11:0]}};

assign p_Result_50_fu_696_p4 = {res_I_V_29_fu_633_p3[14 - 1:7], |(1'd1), res_I_V_29_fu_633_p3[5:0]};

assign p_Result_51_fu_766_p5 = {{x_l_I_V_30_reg_1255[29:21]}, {sub_ln258_6_reg_1273}, {x_l_I_V_30_reg_1255[9:0]}};

assign p_Result_52_fu_776_p4 = {res_I_V_reg_1261[14 - 1:6], |(1'd1), res_I_V_reg_1261[4:0]};

assign p_Result_53_fu_841_p5 = {{x_l_I_V_31_fu_785_p3[29:20]}, {sub_ln258_7_fu_835_p2}, {x_l_I_V_31_fu_785_p3[7:0]}};

assign p_Result_54_fu_853_p4 = {res_I_V_30_fu_791_p3[14 - 1:5], |(1'd1), res_I_V_30_fu_791_p3[3:0]};

assign p_Result_55_fu_923_p5 = {{x_l_I_V_32_reg_1278[29:19]}, {sub_ln258_8_reg_1296}, {x_l_I_V_32_reg_1278[5:0]}};

assign p_Result_56_fu_933_p4 = {res_I_V_31_reg_1284[14 - 1:4], |(1'd1), res_I_V_31_reg_1284[2:0]};

assign p_Result_57_fu_998_p5 = {{x_l_I_V_33_fu_942_p3[29:18]}, {sub_ln258_9_fu_992_p2}, {x_l_I_V_33_fu_942_p3[3:0]}};

assign p_Result_58_fu_1010_p4 = {res_I_V_32_fu_948_p3[14 - 1:3], |(1'd1), res_I_V_32_fu_948_p3[1:0]};

assign p_Result_59_fu_1080_p5 = {{x_l_I_V_34_reg_1301[29:17]}, {sub_ln258_10_reg_1319}, {x_l_I_V_34_reg_1301[1:0]}};

assign p_Result_5_fu_262_p4 = {{x_l_I_V_25_fu_230_p3[26:22]}};

assign p_Result_60_fu_1090_p4 = {res_I_V_33_reg_1307[14 - 1:2], |(1'd1), res_I_V_33_reg_1307[0:0]};

assign p_Result_61_fu_1139_p5 = {{x_l_I_V_35_fu_1099_p3[29:16]}, {sub_ln258_11_fu_1133_p2}};

assign p_Result_62_fu_1151_p4 = {res_I_V_34_fu_1105_p3[14-1:1], |(1'd1)};

assign p_Result_6_fu_483_p4 = {{res_I_V_27_fu_475_p3[13:8]}};

assign p_Result_7_fu_501_p4 = {{x_l_I_V_28_fu_467_p3[23:16]}};

assign p_Result_8_fu_326_p4 = {{res_I_V_25_fu_318_p3[13:10]}};

assign p_Result_9_fu_344_p4 = {{x_l_I_V_26_fu_310_p3[25:20]}};

assign p_Result_s_53_fu_1189_p2 = ((x_l_I_V_36_fu_1161_p3 > zext_ln717_fu_1185_p1) ? 1'b1 : 1'b0);

assign p_Result_s_fu_401_p4 = {{res_I_V_26_fu_395_p3[13:9]}};

assign res_I_V_23_fu_1195_p2 = (res_I_V_35_fu_1169_p3 + 14'd1);

assign res_I_V_25_fu_318_p3 = ((icmp_ln489_1_fu_276_p2[0:0] == 1'b1) ? select_ln239_fu_238_p3 : p_Result_40_fu_300_p4);

assign res_I_V_26_fu_395_p3 = ((icmp_ln489_2_reg_1221[0:0] == 1'b1) ? res_I_V_25_reg_1215 : p_Result_42_fu_380_p4);

assign res_I_V_27_fu_475_p3 = ((icmp_ln489_3_fu_433_p2[0:0] == 1'b1) ? res_I_V_26_fu_395_p3 : p_Result_44_fu_457_p4);

assign res_I_V_28_fu_557_p3 = ((icmp_ln489_4_fu_515_p2[0:0] == 1'b1) ? res_I_V_27_fu_475_p3 : p_Result_46_fu_539_p4);

assign res_I_V_29_fu_633_p3 = ((icmp_ln489_5_fu_596_p2[0:0] == 1'b1) ? res_I_V_28_reg_1238 : p_Result_48_fu_617_p4);

assign res_I_V_30_fu_791_p3 = ((icmp_ln489_7_reg_1267[0:0] == 1'b1) ? res_I_V_reg_1261 : p_Result_52_fu_776_p4);

assign res_I_V_31_fu_871_p3 = ((icmp_ln489_8_fu_829_p2[0:0] == 1'b1) ? res_I_V_30_fu_791_p3 : p_Result_54_fu_853_p4);

assign res_I_V_32_fu_948_p3 = ((icmp_ln489_9_reg_1290[0:0] == 1'b1) ? res_I_V_31_reg_1284 : p_Result_56_fu_933_p4);

assign res_I_V_33_fu_1028_p3 = ((icmp_ln489_10_fu_986_p2[0:0] == 1'b1) ? res_I_V_32_fu_948_p3 : p_Result_58_fu_1010_p4);

assign res_I_V_34_fu_1105_p3 = ((icmp_ln489_11_reg_1313[0:0] == 1'b1) ? res_I_V_33_reg_1307 : p_Result_60_fu_1090_p4);

assign res_I_V_35_fu_1169_p3 = ((icmp_ln489_12_fu_1127_p2[0:0] == 1'b1) ? res_I_V_34_fu_1105_p3 : p_Result_62_fu_1151_p4);

assign res_I_V_fu_714_p3 = ((icmp_ln489_6_fu_672_p2[0:0] == 1'b1) ? res_I_V_29_fu_633_p3 : p_Result_50_fu_696_p4);

assign select_ln239_fu_238_p3 = ((icmp_ln489_fu_202_p2[0:0] == 1'b1) ? 14'd0 : 14'd4096);

assign select_ln489_fu_246_p3 = ((icmp_ln489_fu_202_p2[0:0] == 1'b1) ? 2'd0 : 2'd2);

assign sext_ln323_fu_214_p1 = $signed(add_ln258_fu_208_p2);

assign sub_ln258_10_fu_1074_p2 = (p_Result_31_fu_1054_p4 - zext_ln489_10_fu_1064_p1);

assign sub_ln258_11_fu_1133_p2 = (trunc_ln640_fu_1119_p1 - zext_ln489_11_fu_1123_p1);

assign sub_ln258_1_fu_364_p2 = (p_Result_9_fu_344_p4 - zext_ln489_1_fu_354_p1);

assign sub_ln258_2_fu_439_p2 = (p_Result_1_fu_419_p4 - zext_ln489_2_fu_429_p1);

assign sub_ln258_3_fu_521_p2 = (p_Result_7_fu_501_p4 - zext_ln489_3_fu_511_p1);

assign sub_ln258_4_fu_601_p2 = (p_Result_13_reg_1249 - zext_ln489_4_fu_592_p1);

assign sub_ln258_5_fu_678_p2 = (p_Result_16_fu_658_p4 - zext_ln489_5_fu_668_p1);

assign sub_ln258_6_fu_760_p2 = (p_Result_19_fu_740_p4 - zext_ln489_6_fu_750_p1);

assign sub_ln258_7_fu_835_p2 = (p_Result_22_fu_815_p4 - zext_ln489_7_fu_825_p1);

assign sub_ln258_8_fu_917_p2 = (p_Result_25_fu_897_p4 - zext_ln489_8_fu_907_p1);

assign sub_ln258_9_fu_992_p2 = (p_Result_28_fu_972_p4 - zext_ln489_9_fu_982_p1);

assign sub_ln258_fu_282_p2 = (p_Result_5_fu_262_p4 - zext_ln489_fu_272_p1);

assign tmp_10_fu_1046_p3 = {{p_Result_30_fu_1036_p4}, {1'd1}};

assign tmp_11_fu_1111_p3 = {{res_I_V_34_fu_1105_p3}, {1'd1}};

assign tmp_1_fu_964_p3 = {{p_Result_27_fu_954_p4}, {1'd1}};

assign tmp_2_fu_254_p3 = {{select_ln489_fu_246_p3}, {1'd1}};

assign tmp_3_fu_336_p3 = {{p_Result_8_fu_326_p4}, {1'd1}};

assign tmp_4_fu_411_p3 = {{p_Result_s_fu_401_p4}, {1'd1}};

assign tmp_5_fu_493_p3 = {{p_Result_6_fu_483_p4}, {1'd1}};

assign tmp_6_fu_585_p3 = {{p_Result_12_reg_1244}, {1'd1}};

assign tmp_7_fu_650_p3 = {{p_Result_15_fu_640_p4}, {1'd1}};

assign tmp_8_fu_732_p3 = {{p_Result_18_fu_722_p4}, {1'd1}};

assign tmp_9_fu_807_p3 = {{p_Result_21_fu_797_p4}, {1'd1}};

assign tmp_fu_188_p4 = {{x_int_reg[25:24]}};

assign tmp_s_fu_889_p3 = {{p_Result_24_fu_879_p4}, {1'd1}};

assign trunc_ln640_fu_1119_p1 = x_l_I_V_35_fu_1099_p3[15:0];

assign x_l_I_V_25_fu_230_p3 = ((icmp_ln489_fu_202_p2[0:0] == 1'b1) ? zext_ln712_fu_184_p1 : p_Result_38_fu_218_p5);

assign x_l_I_V_26_fu_310_p3 = ((icmp_ln489_1_fu_276_p2[0:0] == 1'b1) ? x_l_I_V_25_fu_230_p3 : p_Result_39_fu_288_p5);

assign x_l_I_V_27_fu_389_p3 = ((icmp_ln489_2_reg_1221[0:0] == 1'b1) ? x_l_I_V_26_reg_1209 : p_Result_41_fu_370_p5);

assign x_l_I_V_28_fu_467_p3 = ((icmp_ln489_3_fu_433_p2[0:0] == 1'b1) ? x_l_I_V_27_fu_389_p3 : p_Result_43_fu_445_p5);

assign x_l_I_V_29_fu_549_p3 = ((icmp_ln489_4_fu_515_p2[0:0] == 1'b1) ? x_l_I_V_28_fu_467_p3 : p_Result_45_fu_527_p5);

assign x_l_I_V_30_fu_706_p3 = ((icmp_ln489_6_fu_672_p2[0:0] == 1'b1) ? x_l_I_V_fu_626_p3 : p_Result_49_fu_684_p5);

assign x_l_I_V_31_fu_785_p3 = ((icmp_ln489_7_reg_1267[0:0] == 1'b1) ? x_l_I_V_30_reg_1255 : p_Result_51_fu_766_p5);

assign x_l_I_V_32_fu_863_p3 = ((icmp_ln489_8_fu_829_p2[0:0] == 1'b1) ? x_l_I_V_31_fu_785_p3 : p_Result_53_fu_841_p5);

assign x_l_I_V_33_fu_942_p3 = ((icmp_ln489_9_reg_1290[0:0] == 1'b1) ? x_l_I_V_32_reg_1278 : p_Result_55_fu_923_p5);

assign x_l_I_V_34_fu_1020_p3 = ((icmp_ln489_10_fu_986_p2[0:0] == 1'b1) ? x_l_I_V_33_fu_942_p3 : p_Result_57_fu_998_p5);

assign x_l_I_V_35_fu_1099_p3 = ((icmp_ln489_11_reg_1313[0:0] == 1'b1) ? x_l_I_V_34_reg_1301 : p_Result_59_fu_1080_p5);

assign x_l_I_V_36_fu_1161_p3 = ((icmp_ln489_12_fu_1127_p2[0:0] == 1'b1) ? x_l_I_V_35_fu_1099_p3 : p_Result_61_fu_1139_p5);

assign x_l_I_V_fu_626_p3 = ((icmp_ln489_5_fu_596_p2[0:0] == 1'b1) ? x_l_I_V_29_reg_1232 : p_Result_47_fu_606_p5);

assign zext_ln489_10_fu_1064_p1 = tmp_10_fu_1046_p3;

assign zext_ln489_11_fu_1123_p1 = tmp_11_fu_1111_p3;

assign zext_ln489_12_fu_198_p1 = tmp_fu_188_p4;

assign zext_ln489_1_fu_354_p1 = tmp_3_fu_336_p3;

assign zext_ln489_2_fu_429_p1 = tmp_4_fu_411_p3;

assign zext_ln489_3_fu_511_p1 = tmp_5_fu_493_p3;

assign zext_ln489_4_fu_592_p1 = tmp_6_fu_585_p3;

assign zext_ln489_5_fu_668_p1 = tmp_7_fu_650_p3;

assign zext_ln489_6_fu_750_p1 = tmp_8_fu_732_p3;

assign zext_ln489_7_fu_825_p1 = tmp_9_fu_807_p3;

assign zext_ln489_8_fu_907_p1 = tmp_s_fu_889_p3;

assign zext_ln489_9_fu_982_p1 = tmp_1_fu_964_p3;

assign zext_ln489_fu_272_p1 = tmp_2_fu_254_p3;

assign zext_ln712_fu_184_p1 = x_int_reg;

assign zext_ln717_fu_1185_p1 = mul_I_V_fu_1177_p3;

endmodule //eucDis_sqrt_fixed_27_27_s
