// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module eucDis_sqrt_fixed_33_33_s (
        ap_clk,
        ap_rst,
        x,
        ap_return
);


input   ap_clk;
input   ap_rst;
input  [31:0] x;
output  [16:0] ap_return;

wire   [0:0] icmp_ln443_fu_234_p2;
reg   [0:0] icmp_ln443_reg_1467;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_pp0_stage0_11001;
wire   [35:0] x_l_I_V_31_fu_262_p3;
reg   [35:0] x_l_I_V_31_reg_1472;
wire   [0:0] icmp_ln443_1_fu_300_p2;
reg   [0:0] icmp_ln443_1_reg_1478;
wire   [4:0] sub_ln212_fu_306_p2;
reg   [4:0] sub_ln212_reg_1484;
wire   [35:0] x_l_I_V_33_fu_418_p3;
reg   [35:0] x_l_I_V_33_reg_1489;
wire   [16:0] res_I_V_32_fu_426_p3;
reg   [16:0] res_I_V_32_reg_1495;
wire   [0:0] icmp_ln443_3_fu_466_p2;
reg   [0:0] icmp_ln443_3_reg_1501;
wire   [6:0] sub_ln212_2_fu_472_p2;
reg   [6:0] sub_ln212_2_reg_1507;
wire   [35:0] x_l_I_V_35_fu_575_p3;
reg   [35:0] x_l_I_V_35_reg_1512;
wire   [16:0] res_I_V_34_fu_583_p3;
reg   [16:0] res_I_V_34_reg_1518;
wire   [0:0] icmp_ln443_5_fu_623_p2;
reg   [0:0] icmp_ln443_5_reg_1524;
wire   [8:0] sub_ln212_4_fu_629_p2;
reg   [8:0] sub_ln212_4_reg_1530;
wire   [35:0] x_l_I_V_36_fu_732_p3;
reg   [35:0] x_l_I_V_36_reg_1535;
wire   [16:0] res_I_V_fu_740_p3;
reg   [16:0] res_I_V_reg_1541;
wire   [0:0] icmp_ln443_7_fu_780_p2;
reg   [0:0] icmp_ln443_7_reg_1547;
wire   [10:0] sub_ln212_6_fu_786_p2;
reg   [10:0] sub_ln212_6_reg_1553;
wire   [35:0] x_l_I_V_38_fu_889_p3;
reg   [35:0] x_l_I_V_38_reg_1558;
wire   [16:0] res_I_V_37_fu_897_p3;
reg   [16:0] res_I_V_37_reg_1564;
wire   [0:0] icmp_ln443_9_fu_937_p2;
reg   [0:0] icmp_ln443_9_reg_1570;
wire   [12:0] sub_ln212_8_fu_943_p2;
reg   [12:0] sub_ln212_8_reg_1576;
wire   [35:0] x_l_I_V_40_fu_1046_p3;
reg   [35:0] x_l_I_V_40_reg_1581;
wire   [16:0] res_I_V_39_fu_1054_p3;
reg   [16:0] res_I_V_39_reg_1587;
wire   [0:0] icmp_ln443_11_fu_1094_p2;
reg   [0:0] icmp_ln443_11_reg_1593;
wire   [14:0] sub_ln212_10_fu_1100_p2;
reg   [14:0] sub_ln212_10_reg_1599;
wire   [35:0] x_l_I_V_42_fu_1203_p3;
reg   [35:0] x_l_I_V_42_reg_1604;
wire   [16:0] res_I_V_41_fu_1211_p3;
reg   [16:0] res_I_V_41_reg_1610;
wire   [0:0] icmp_ln443_13_fu_1251_p2;
reg   [0:0] icmp_ln443_13_reg_1616;
wire   [16:0] sub_ln212_12_fu_1257_p2;
reg   [16:0] sub_ln212_12_reg_1622;
wire   [35:0] x_l_I_V_44_fu_1360_p3;
reg   [35:0] x_l_I_V_44_reg_1627;
wire   [16:0] res_I_V_43_fu_1368_p3;
reg   [16:0] res_I_V_43_reg_1633;
wire   [18:0] p_Result_92_fu_1376_p1;
reg   [18:0] p_Result_92_reg_1640;
wire    ap_block_pp0_stage0;
wire   [1:0] p_Result_48_fu_220_p4;
wire   [2:0] zext_ln594_fu_230_p1;
wire   [2:0] add_ln212_fu_240_p2;
wire   [35:0] zext_ln666_fu_216_p1;
wire  signed [3:0] sext_ln277_fu_246_p1;
wire   [35:0] p_Result_49_fu_250_p5;
wire   [1:0] select_ln443_fu_270_p3;
wire   [2:0] tmp_fu_278_p3;
wire   [4:0] p_Result_50_fu_286_p4;
wire   [4:0] zext_ln443_fu_296_p1;
wire   [16:0] select_ln239_fu_312_p3;
wire   [35:0] p_Result_51_fu_319_p5;
wire   [16:0] p_Result_52_fu_329_p4;
wire   [16:0] res_I_V_31_fu_345_p3;
wire   [3:0] p_Result_8_fu_352_p4;
wire   [35:0] x_l_I_V_32_fu_339_p3;
wire   [4:0] tmp_3_fu_362_p3;
wire   [5:0] p_Result_53_fu_370_p4;
wire   [5:0] zext_ln443_1_fu_380_p1;
wire   [5:0] sub_ln212_1_fu_390_p2;
wire   [0:0] icmp_ln443_2_fu_384_p2;
wire   [35:0] p_Result_54_fu_396_p5;
wire   [16:0] p_Result_55_fu_408_p4;
wire   [4:0] p_Result_s_fu_434_p4;
wire   [5:0] tmp_4_fu_444_p3;
wire   [6:0] p_Result_56_fu_452_p4;
wire   [6:0] zext_ln443_2_fu_462_p1;
wire   [35:0] p_Result_57_fu_478_p5;
wire   [16:0] p_Result_58_fu_488_p4;
wire   [16:0] res_I_V_33_fu_503_p3;
wire   [5:0] p_Result_5_fu_509_p4;
wire   [35:0] x_l_I_V_34_fu_497_p3;
wire   [6:0] tmp_5_fu_519_p3;
wire   [7:0] p_Result_59_fu_527_p4;
wire   [7:0] zext_ln443_3_fu_537_p1;
wire   [7:0] sub_ln212_3_fu_547_p2;
wire   [0:0] icmp_ln443_4_fu_541_p2;
wire   [35:0] p_Result_60_fu_553_p5;
wire   [16:0] p_Result_61_fu_565_p4;
wire   [6:0] p_Result_10_fu_591_p4;
wire   [7:0] tmp_6_fu_601_p3;
wire   [8:0] p_Result_62_fu_609_p4;
wire   [8:0] zext_ln443_4_fu_619_p1;
wire   [35:0] p_Result_63_fu_635_p5;
wire   [16:0] p_Result_64_fu_645_p4;
wire   [16:0] res_I_V_35_fu_660_p3;
wire   [7:0] p_Result_14_fu_666_p4;
wire   [35:0] x_l_I_V_fu_654_p3;
wire   [8:0] tmp_7_fu_676_p3;
wire   [9:0] p_Result_65_fu_684_p4;
wire   [9:0] zext_ln443_5_fu_694_p1;
wire   [9:0] sub_ln212_5_fu_704_p2;
wire   [0:0] icmp_ln443_6_fu_698_p2;
wire   [35:0] p_Result_66_fu_710_p5;
wire   [16:0] p_Result_67_fu_722_p4;
wire   [8:0] p_Result_18_fu_748_p4;
wire   [9:0] tmp_8_fu_758_p3;
wire   [10:0] p_Result_68_fu_766_p4;
wire   [10:0] zext_ln443_6_fu_776_p1;
wire   [35:0] p_Result_69_fu_792_p5;
wire   [16:0] p_Result_70_fu_802_p4;
wire   [16:0] res_I_V_36_fu_817_p3;
wire   [9:0] p_Result_21_fu_823_p4;
wire   [35:0] x_l_I_V_37_fu_811_p3;
wire   [10:0] tmp_9_fu_833_p3;
wire   [11:0] p_Result_71_fu_841_p4;
wire   [11:0] zext_ln443_7_fu_851_p1;
wire   [11:0] sub_ln212_7_fu_861_p2;
wire   [0:0] icmp_ln443_8_fu_855_p2;
wire   [35:0] p_Result_72_fu_867_p5;
wire   [16:0] p_Result_73_fu_879_p4;
wire   [10:0] p_Result_24_fu_905_p4;
wire   [11:0] tmp_s_fu_915_p3;
wire   [12:0] p_Result_74_fu_923_p4;
wire   [12:0] zext_ln443_8_fu_933_p1;
wire   [35:0] p_Result_75_fu_949_p5;
wire   [16:0] p_Result_76_fu_959_p4;
wire   [16:0] res_I_V_38_fu_974_p3;
wire   [11:0] p_Result_27_fu_980_p4;
wire   [35:0] x_l_I_V_39_fu_968_p3;
wire   [12:0] tmp_1_fu_990_p3;
wire   [13:0] p_Result_77_fu_998_p4;
wire   [13:0] zext_ln443_9_fu_1008_p1;
wire   [13:0] sub_ln212_9_fu_1018_p2;
wire   [0:0] icmp_ln443_10_fu_1012_p2;
wire   [35:0] p_Result_78_fu_1024_p5;
wire   [16:0] p_Result_79_fu_1036_p4;
wire   [12:0] p_Result_30_fu_1062_p4;
wire   [13:0] tmp_2_fu_1072_p3;
wire   [14:0] p_Result_80_fu_1080_p4;
wire   [14:0] zext_ln443_10_fu_1090_p1;
wire   [35:0] p_Result_81_fu_1106_p5;
wire   [16:0] p_Result_82_fu_1116_p4;
wire   [16:0] res_I_V_40_fu_1131_p3;
wire   [13:0] p_Result_33_fu_1137_p4;
wire   [35:0] x_l_I_V_41_fu_1125_p3;
wire   [14:0] tmp_10_fu_1147_p3;
wire   [15:0] p_Result_83_fu_1155_p4;
wire   [15:0] zext_ln443_11_fu_1165_p1;
wire   [15:0] sub_ln212_11_fu_1175_p2;
wire   [0:0] icmp_ln443_12_fu_1169_p2;
wire   [35:0] p_Result_84_fu_1181_p5;
wire   [16:0] p_Result_85_fu_1193_p4;
wire   [14:0] p_Result_36_fu_1219_p4;
wire   [15:0] tmp_11_fu_1229_p3;
wire   [16:0] p_Result_86_fu_1237_p4;
wire   [16:0] zext_ln443_12_fu_1247_p1;
wire   [35:0] p_Result_87_fu_1263_p5;
wire   [16:0] p_Result_88_fu_1273_p4;
wire   [16:0] res_I_V_42_fu_1288_p3;
wire   [15:0] p_Result_39_fu_1294_p4;
wire   [35:0] x_l_I_V_43_fu_1282_p3;
wire   [16:0] tmp_12_fu_1304_p3;
wire   [17:0] p_Result_89_fu_1312_p4;
wire   [17:0] zext_ln443_13_fu_1322_p1;
wire   [17:0] sub_ln212_13_fu_1332_p2;
wire   [0:0] icmp_ln443_14_fu_1326_p2;
wire   [35:0] p_Result_90_fu_1338_p5;
wire   [16:0] p_Result_91_fu_1350_p4;
wire   [17:0] tmp_13_fu_1380_p3;
wire   [18:0] zext_ln443_14_fu_1387_p1;
wire   [18:0] sub_ln212_14_fu_1396_p2;
wire   [0:0] icmp_ln443_15_fu_1391_p2;
wire   [35:0] p_Result_93_fu_1401_p5;
wire   [16:0] p_Result_94_fu_1412_p4;
wire   [16:0] res_I_V_44_fu_1428_p3;
wire   [33:0] mul_I_V_fu_1435_p3;
wire   [35:0] x_l_I_V_45_fu_1421_p3;
wire   [35:0] zext_ln671_fu_1443_p1;
wire   [0:0] p_Result_s_60_fu_1447_p2;
wire   [16:0] res_I_V_29_fu_1453_p2;
reg   [31:0] x_int_reg;
wire    ap_ce_reg;

always @ (posedge ap_clk) begin
    x_int_reg <= x;
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln443_11_reg_1593 <= icmp_ln443_11_fu_1094_p2;
        icmp_ln443_13_reg_1616 <= icmp_ln443_13_fu_1251_p2;
        icmp_ln443_1_reg_1478 <= icmp_ln443_1_fu_300_p2;
        icmp_ln443_3_reg_1501 <= icmp_ln443_3_fu_466_p2;
        icmp_ln443_5_reg_1524 <= icmp_ln443_5_fu_623_p2;
        icmp_ln443_7_reg_1547 <= icmp_ln443_7_fu_780_p2;
        icmp_ln443_9_reg_1570 <= icmp_ln443_9_fu_937_p2;
        icmp_ln443_reg_1467 <= icmp_ln443_fu_234_p2;
        p_Result_92_reg_1640 <= p_Result_92_fu_1376_p1;
        res_I_V_32_reg_1495 <= res_I_V_32_fu_426_p3;
        res_I_V_34_reg_1518 <= res_I_V_34_fu_583_p3;
        res_I_V_37_reg_1564 <= res_I_V_37_fu_897_p3;
        res_I_V_39_reg_1587 <= res_I_V_39_fu_1054_p3;
        res_I_V_41_reg_1610 <= res_I_V_41_fu_1211_p3;
        res_I_V_43_reg_1633 <= res_I_V_43_fu_1368_p3;
        res_I_V_reg_1541 <= res_I_V_fu_740_p3;
        sub_ln212_10_reg_1599 <= sub_ln212_10_fu_1100_p2;
        sub_ln212_12_reg_1622 <= sub_ln212_12_fu_1257_p2;
        sub_ln212_2_reg_1507 <= sub_ln212_2_fu_472_p2;
        sub_ln212_4_reg_1530 <= sub_ln212_4_fu_629_p2;
        sub_ln212_6_reg_1553 <= sub_ln212_6_fu_786_p2;
        sub_ln212_8_reg_1576 <= sub_ln212_8_fu_943_p2;
        sub_ln212_reg_1484 <= sub_ln212_fu_306_p2;
        x_l_I_V_31_reg_1472 <= x_l_I_V_31_fu_262_p3;
        x_l_I_V_33_reg_1489 <= x_l_I_V_33_fu_418_p3;
        x_l_I_V_35_reg_1512 <= x_l_I_V_35_fu_575_p3;
        x_l_I_V_36_reg_1535 <= x_l_I_V_36_fu_732_p3;
        x_l_I_V_38_reg_1558 <= x_l_I_V_38_fu_889_p3;
        x_l_I_V_40_reg_1581 <= x_l_I_V_40_fu_1046_p3;
        x_l_I_V_42_reg_1604 <= x_l_I_V_42_fu_1203_p3;
        x_l_I_V_44_reg_1627 <= x_l_I_V_44_fu_1360_p3;
    end
end

assign add_ln212_fu_240_p2 = ($signed(zext_ln594_fu_230_p1) + $signed(3'd7));

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_return = ((p_Result_s_60_fu_1447_p2[0:0] == 1'b1) ? res_I_V_29_fu_1453_p2 : res_I_V_44_fu_1428_p3);

assign icmp_ln443_10_fu_1012_p2 = ((p_Result_77_fu_998_p4 < zext_ln443_9_fu_1008_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_11_fu_1094_p2 = ((p_Result_80_fu_1080_p4 < zext_ln443_10_fu_1090_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_12_fu_1169_p2 = ((p_Result_83_fu_1155_p4 < zext_ln443_11_fu_1165_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_13_fu_1251_p2 = ((p_Result_86_fu_1237_p4 < zext_ln443_12_fu_1247_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_14_fu_1326_p2 = ((p_Result_89_fu_1312_p4 < zext_ln443_13_fu_1322_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_15_fu_1391_p2 = ((p_Result_92_reg_1640 < zext_ln443_14_fu_1387_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_1_fu_300_p2 = ((p_Result_50_fu_286_p4 < zext_ln443_fu_296_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_2_fu_384_p2 = ((p_Result_53_fu_370_p4 < zext_ln443_1_fu_380_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_3_fu_466_p2 = ((p_Result_56_fu_452_p4 < zext_ln443_2_fu_462_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_4_fu_541_p2 = ((p_Result_59_fu_527_p4 < zext_ln443_3_fu_537_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_5_fu_623_p2 = ((p_Result_62_fu_609_p4 < zext_ln443_4_fu_619_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_6_fu_698_p2 = ((p_Result_65_fu_684_p4 < zext_ln443_5_fu_694_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_7_fu_780_p2 = ((p_Result_68_fu_766_p4 < zext_ln443_6_fu_776_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_8_fu_855_p2 = ((p_Result_71_fu_841_p4 < zext_ln443_7_fu_851_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_9_fu_937_p2 = ((p_Result_74_fu_923_p4 < zext_ln443_8_fu_933_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_fu_234_p2 = ((p_Result_48_fu_220_p4 == 2'd0) ? 1'b1 : 1'b0);

assign mul_I_V_fu_1435_p3 = {{17'd0}, {res_I_V_44_fu_1428_p3}};

assign p_Result_10_fu_591_p4 = {{res_I_V_34_fu_583_p3[16:10]}};

assign p_Result_14_fu_666_p4 = {{res_I_V_35_fu_660_p3[16:9]}};

assign p_Result_18_fu_748_p4 = {{res_I_V_fu_740_p3[16:8]}};

assign p_Result_21_fu_823_p4 = {{res_I_V_36_fu_817_p3[16:7]}};

assign p_Result_24_fu_905_p4 = {{res_I_V_37_fu_897_p3[16:6]}};

assign p_Result_27_fu_980_p4 = {{res_I_V_38_fu_974_p3[16:5]}};

assign p_Result_30_fu_1062_p4 = {{res_I_V_39_fu_1054_p3[16:4]}};

assign p_Result_33_fu_1137_p4 = {{res_I_V_40_fu_1131_p3[16:3]}};

assign p_Result_36_fu_1219_p4 = {{res_I_V_41_fu_1211_p3[16:2]}};

assign p_Result_39_fu_1294_p4 = {{res_I_V_42_fu_1288_p3[16:1]}};

assign p_Result_48_fu_220_p4 = {{x_int_reg[31:30]}};

assign p_Result_49_fu_250_p5 = {{zext_ln666_fu_216_p1[35:34]}, {sext_ln277_fu_246_p1}, {zext_ln666_fu_216_p1[29:0]}};

assign p_Result_50_fu_286_p4 = {{x_l_I_V_31_fu_262_p3[32:28]}};

assign p_Result_51_fu_319_p5 = {{x_l_I_V_31_reg_1472[35:33]}, {sub_ln212_reg_1484}, {x_l_I_V_31_reg_1472[27:0]}};

assign p_Result_52_fu_329_p4 = {select_ln239_fu_312_p3[17 - 1:15], |(1'd1), select_ln239_fu_312_p3[13:0]};

assign p_Result_53_fu_370_p4 = {{x_l_I_V_32_fu_339_p3[31:26]}};

assign p_Result_54_fu_396_p5 = {{x_l_I_V_32_fu_339_p3[35:32]}, {sub_ln212_1_fu_390_p2}, {x_l_I_V_32_fu_339_p3[25:0]}};

assign p_Result_55_fu_408_p4 = {res_I_V_31_fu_345_p3[17 - 1:14], |(1'd1), res_I_V_31_fu_345_p3[12:0]};

assign p_Result_56_fu_452_p4 = {{x_l_I_V_33_fu_418_p3[30:24]}};

assign p_Result_57_fu_478_p5 = {{x_l_I_V_33_reg_1489[35:31]}, {sub_ln212_2_reg_1507}, {x_l_I_V_33_reg_1489[23:0]}};

assign p_Result_58_fu_488_p4 = {res_I_V_32_reg_1495[17 - 1:13], |(1'd1), res_I_V_32_reg_1495[11:0]};

assign p_Result_59_fu_527_p4 = {{x_l_I_V_34_fu_497_p3[29:22]}};

assign p_Result_5_fu_509_p4 = {{res_I_V_33_fu_503_p3[16:11]}};

assign p_Result_60_fu_553_p5 = {{x_l_I_V_34_fu_497_p3[35:30]}, {sub_ln212_3_fu_547_p2}, {x_l_I_V_34_fu_497_p3[21:0]}};

assign p_Result_61_fu_565_p4 = {res_I_V_33_fu_503_p3[17 - 1:12], |(1'd1), res_I_V_33_fu_503_p3[10:0]};

assign p_Result_62_fu_609_p4 = {{x_l_I_V_35_fu_575_p3[28:20]}};

assign p_Result_63_fu_635_p5 = {{x_l_I_V_35_reg_1512[35:29]}, {sub_ln212_4_reg_1530}, {x_l_I_V_35_reg_1512[19:0]}};

assign p_Result_64_fu_645_p4 = {res_I_V_34_reg_1518[17 - 1:11], |(1'd1), res_I_V_34_reg_1518[9:0]};

assign p_Result_65_fu_684_p4 = {{x_l_I_V_fu_654_p3[27:18]}};

assign p_Result_66_fu_710_p5 = {{x_l_I_V_fu_654_p3[35:28]}, {sub_ln212_5_fu_704_p2}, {x_l_I_V_fu_654_p3[17:0]}};

assign p_Result_67_fu_722_p4 = {res_I_V_35_fu_660_p3[17 - 1:10], |(1'd1), res_I_V_35_fu_660_p3[8:0]};

assign p_Result_68_fu_766_p4 = {{x_l_I_V_36_fu_732_p3[26:16]}};

assign p_Result_69_fu_792_p5 = {{x_l_I_V_36_reg_1535[35:27]}, {sub_ln212_6_reg_1553}, {x_l_I_V_36_reg_1535[15:0]}};

assign p_Result_70_fu_802_p4 = {res_I_V_reg_1541[17 - 1:9], |(1'd1), res_I_V_reg_1541[7:0]};

assign p_Result_71_fu_841_p4 = {{x_l_I_V_37_fu_811_p3[25:14]}};

assign p_Result_72_fu_867_p5 = {{x_l_I_V_37_fu_811_p3[35:26]}, {sub_ln212_7_fu_861_p2}, {x_l_I_V_37_fu_811_p3[13:0]}};

assign p_Result_73_fu_879_p4 = {res_I_V_36_fu_817_p3[17 - 1:8], |(1'd1), res_I_V_36_fu_817_p3[6:0]};

assign p_Result_74_fu_923_p4 = {{x_l_I_V_38_fu_889_p3[24:12]}};

assign p_Result_75_fu_949_p5 = {{x_l_I_V_38_reg_1558[35:25]}, {sub_ln212_8_reg_1576}, {x_l_I_V_38_reg_1558[11:0]}};

assign p_Result_76_fu_959_p4 = {res_I_V_37_reg_1564[17 - 1:7], |(1'd1), res_I_V_37_reg_1564[5:0]};

assign p_Result_77_fu_998_p4 = {{x_l_I_V_39_fu_968_p3[23:10]}};

assign p_Result_78_fu_1024_p5 = {{x_l_I_V_39_fu_968_p3[35:24]}, {sub_ln212_9_fu_1018_p2}, {x_l_I_V_39_fu_968_p3[9:0]}};

assign p_Result_79_fu_1036_p4 = {res_I_V_38_fu_974_p3[17 - 1:6], |(1'd1), res_I_V_38_fu_974_p3[4:0]};

assign p_Result_80_fu_1080_p4 = {{x_l_I_V_40_fu_1046_p3[22:8]}};

assign p_Result_81_fu_1106_p5 = {{x_l_I_V_40_reg_1581[35:23]}, {sub_ln212_10_reg_1599}, {x_l_I_V_40_reg_1581[7:0]}};

assign p_Result_82_fu_1116_p4 = {res_I_V_39_reg_1587[17 - 1:5], |(1'd1), res_I_V_39_reg_1587[3:0]};

assign p_Result_83_fu_1155_p4 = {{x_l_I_V_41_fu_1125_p3[21:6]}};

assign p_Result_84_fu_1181_p5 = {{x_l_I_V_41_fu_1125_p3[35:22]}, {sub_ln212_11_fu_1175_p2}, {x_l_I_V_41_fu_1125_p3[5:0]}};

assign p_Result_85_fu_1193_p4 = {res_I_V_40_fu_1131_p3[17 - 1:4], |(1'd1), res_I_V_40_fu_1131_p3[2:0]};

assign p_Result_86_fu_1237_p4 = {{x_l_I_V_42_fu_1203_p3[20:4]}};

assign p_Result_87_fu_1263_p5 = {{x_l_I_V_42_reg_1604[35:21]}, {sub_ln212_12_reg_1622}, {x_l_I_V_42_reg_1604[3:0]}};

assign p_Result_88_fu_1273_p4 = {res_I_V_41_reg_1610[17 - 1:3], |(1'd1), res_I_V_41_reg_1610[1:0]};

assign p_Result_89_fu_1312_p4 = {{x_l_I_V_43_fu_1282_p3[19:2]}};

assign p_Result_8_fu_352_p4 = {{res_I_V_31_fu_345_p3[16:13]}};

assign p_Result_90_fu_1338_p5 = {{x_l_I_V_43_fu_1282_p3[35:20]}, {sub_ln212_13_fu_1332_p2}, {x_l_I_V_43_fu_1282_p3[1:0]}};

assign p_Result_91_fu_1350_p4 = {res_I_V_42_fu_1288_p3[17 - 1:2], |(1'd1), res_I_V_42_fu_1288_p3[0:0]};

assign p_Result_92_fu_1376_p1 = x_l_I_V_44_fu_1360_p3[18:0];

assign p_Result_93_fu_1401_p5 = {{x_l_I_V_44_reg_1627[35:19]}, {sub_ln212_14_fu_1396_p2}};

assign p_Result_94_fu_1412_p4 = {res_I_V_43_reg_1633[17-1:1], |(1'd1)};

assign p_Result_s_60_fu_1447_p2 = ((x_l_I_V_45_fu_1421_p3 > zext_ln671_fu_1443_p1) ? 1'b1 : 1'b0);

assign p_Result_s_fu_434_p4 = {{res_I_V_32_fu_426_p3[16:12]}};

assign res_I_V_29_fu_1453_p2 = (res_I_V_44_fu_1428_p3 + 17'd1);

assign res_I_V_31_fu_345_p3 = ((icmp_ln443_1_reg_1478[0:0] == 1'b1) ? select_ln239_fu_312_p3 : p_Result_52_fu_329_p4);

assign res_I_V_32_fu_426_p3 = ((icmp_ln443_2_fu_384_p2[0:0] == 1'b1) ? res_I_V_31_fu_345_p3 : p_Result_55_fu_408_p4);

assign res_I_V_33_fu_503_p3 = ((icmp_ln443_3_reg_1501[0:0] == 1'b1) ? res_I_V_32_reg_1495 : p_Result_58_fu_488_p4);

assign res_I_V_34_fu_583_p3 = ((icmp_ln443_4_fu_541_p2[0:0] == 1'b1) ? res_I_V_33_fu_503_p3 : p_Result_61_fu_565_p4);

assign res_I_V_35_fu_660_p3 = ((icmp_ln443_5_reg_1524[0:0] == 1'b1) ? res_I_V_34_reg_1518 : p_Result_64_fu_645_p4);

assign res_I_V_36_fu_817_p3 = ((icmp_ln443_7_reg_1547[0:0] == 1'b1) ? res_I_V_reg_1541 : p_Result_70_fu_802_p4);

assign res_I_V_37_fu_897_p3 = ((icmp_ln443_8_fu_855_p2[0:0] == 1'b1) ? res_I_V_36_fu_817_p3 : p_Result_73_fu_879_p4);

assign res_I_V_38_fu_974_p3 = ((icmp_ln443_9_reg_1570[0:0] == 1'b1) ? res_I_V_37_reg_1564 : p_Result_76_fu_959_p4);

assign res_I_V_39_fu_1054_p3 = ((icmp_ln443_10_fu_1012_p2[0:0] == 1'b1) ? res_I_V_38_fu_974_p3 : p_Result_79_fu_1036_p4);

assign res_I_V_40_fu_1131_p3 = ((icmp_ln443_11_reg_1593[0:0] == 1'b1) ? res_I_V_39_reg_1587 : p_Result_82_fu_1116_p4);

assign res_I_V_41_fu_1211_p3 = ((icmp_ln443_12_fu_1169_p2[0:0] == 1'b1) ? res_I_V_40_fu_1131_p3 : p_Result_85_fu_1193_p4);

assign res_I_V_42_fu_1288_p3 = ((icmp_ln443_13_reg_1616[0:0] == 1'b1) ? res_I_V_41_reg_1610 : p_Result_88_fu_1273_p4);

assign res_I_V_43_fu_1368_p3 = ((icmp_ln443_14_fu_1326_p2[0:0] == 1'b1) ? res_I_V_42_fu_1288_p3 : p_Result_91_fu_1350_p4);

assign res_I_V_44_fu_1428_p3 = ((icmp_ln443_15_fu_1391_p2[0:0] == 1'b1) ? res_I_V_43_reg_1633 : p_Result_94_fu_1412_p4);

assign res_I_V_fu_740_p3 = ((icmp_ln443_6_fu_698_p2[0:0] == 1'b1) ? res_I_V_35_fu_660_p3 : p_Result_67_fu_722_p4);

assign select_ln239_fu_312_p3 = ((icmp_ln443_reg_1467[0:0] == 1'b1) ? 17'd0 : 17'd32768);

assign select_ln443_fu_270_p3 = ((icmp_ln443_fu_234_p2[0:0] == 1'b1) ? 2'd0 : 2'd2);

assign sext_ln277_fu_246_p1 = $signed(add_ln212_fu_240_p2);

assign sub_ln212_10_fu_1100_p2 = (p_Result_80_fu_1080_p4 - zext_ln443_10_fu_1090_p1);

assign sub_ln212_11_fu_1175_p2 = (p_Result_83_fu_1155_p4 - zext_ln443_11_fu_1165_p1);

assign sub_ln212_12_fu_1257_p2 = (p_Result_86_fu_1237_p4 - zext_ln443_12_fu_1247_p1);

assign sub_ln212_13_fu_1332_p2 = (p_Result_89_fu_1312_p4 - zext_ln443_13_fu_1322_p1);

assign sub_ln212_14_fu_1396_p2 = (p_Result_92_reg_1640 - zext_ln443_14_fu_1387_p1);

assign sub_ln212_1_fu_390_p2 = (p_Result_53_fu_370_p4 - zext_ln443_1_fu_380_p1);

assign sub_ln212_2_fu_472_p2 = (p_Result_56_fu_452_p4 - zext_ln443_2_fu_462_p1);

assign sub_ln212_3_fu_547_p2 = (p_Result_59_fu_527_p4 - zext_ln443_3_fu_537_p1);

assign sub_ln212_4_fu_629_p2 = (p_Result_62_fu_609_p4 - zext_ln443_4_fu_619_p1);

assign sub_ln212_5_fu_704_p2 = (p_Result_65_fu_684_p4 - zext_ln443_5_fu_694_p1);

assign sub_ln212_6_fu_786_p2 = (p_Result_68_fu_766_p4 - zext_ln443_6_fu_776_p1);

assign sub_ln212_7_fu_861_p2 = (p_Result_71_fu_841_p4 - zext_ln443_7_fu_851_p1);

assign sub_ln212_8_fu_943_p2 = (p_Result_74_fu_923_p4 - zext_ln443_8_fu_933_p1);

assign sub_ln212_9_fu_1018_p2 = (p_Result_77_fu_998_p4 - zext_ln443_9_fu_1008_p1);

assign sub_ln212_fu_306_p2 = (p_Result_50_fu_286_p4 - zext_ln443_fu_296_p1);

assign tmp_10_fu_1147_p3 = {{p_Result_33_fu_1137_p4}, {1'd1}};

assign tmp_11_fu_1229_p3 = {{p_Result_36_fu_1219_p4}, {1'd1}};

assign tmp_12_fu_1304_p3 = {{p_Result_39_fu_1294_p4}, {1'd1}};

assign tmp_13_fu_1380_p3 = {{res_I_V_43_reg_1633}, {1'd1}};

assign tmp_1_fu_990_p3 = {{p_Result_27_fu_980_p4}, {1'd1}};

assign tmp_2_fu_1072_p3 = {{p_Result_30_fu_1062_p4}, {1'd1}};

assign tmp_3_fu_362_p3 = {{p_Result_8_fu_352_p4}, {1'd1}};

assign tmp_4_fu_444_p3 = {{p_Result_s_fu_434_p4}, {1'd1}};

assign tmp_5_fu_519_p3 = {{p_Result_5_fu_509_p4}, {1'd1}};

assign tmp_6_fu_601_p3 = {{p_Result_10_fu_591_p4}, {1'd1}};

assign tmp_7_fu_676_p3 = {{p_Result_14_fu_666_p4}, {1'd1}};

assign tmp_8_fu_758_p3 = {{p_Result_18_fu_748_p4}, {1'd1}};

assign tmp_9_fu_833_p3 = {{p_Result_21_fu_823_p4}, {1'd1}};

assign tmp_fu_278_p3 = {{select_ln443_fu_270_p3}, {1'd1}};

assign tmp_s_fu_915_p3 = {{p_Result_24_fu_905_p4}, {1'd1}};

assign x_l_I_V_31_fu_262_p3 = ((icmp_ln443_fu_234_p2[0:0] == 1'b1) ? zext_ln666_fu_216_p1 : p_Result_49_fu_250_p5);

assign x_l_I_V_32_fu_339_p3 = ((icmp_ln443_1_reg_1478[0:0] == 1'b1) ? x_l_I_V_31_reg_1472 : p_Result_51_fu_319_p5);

assign x_l_I_V_33_fu_418_p3 = ((icmp_ln443_2_fu_384_p2[0:0] == 1'b1) ? x_l_I_V_32_fu_339_p3 : p_Result_54_fu_396_p5);

assign x_l_I_V_34_fu_497_p3 = ((icmp_ln443_3_reg_1501[0:0] == 1'b1) ? x_l_I_V_33_reg_1489 : p_Result_57_fu_478_p5);

assign x_l_I_V_35_fu_575_p3 = ((icmp_ln443_4_fu_541_p2[0:0] == 1'b1) ? x_l_I_V_34_fu_497_p3 : p_Result_60_fu_553_p5);

assign x_l_I_V_36_fu_732_p3 = ((icmp_ln443_6_fu_698_p2[0:0] == 1'b1) ? x_l_I_V_fu_654_p3 : p_Result_66_fu_710_p5);

assign x_l_I_V_37_fu_811_p3 = ((icmp_ln443_7_reg_1547[0:0] == 1'b1) ? x_l_I_V_36_reg_1535 : p_Result_69_fu_792_p5);

assign x_l_I_V_38_fu_889_p3 = ((icmp_ln443_8_fu_855_p2[0:0] == 1'b1) ? x_l_I_V_37_fu_811_p3 : p_Result_72_fu_867_p5);

assign x_l_I_V_39_fu_968_p3 = ((icmp_ln443_9_reg_1570[0:0] == 1'b1) ? x_l_I_V_38_reg_1558 : p_Result_75_fu_949_p5);

assign x_l_I_V_40_fu_1046_p3 = ((icmp_ln443_10_fu_1012_p2[0:0] == 1'b1) ? x_l_I_V_39_fu_968_p3 : p_Result_78_fu_1024_p5);

assign x_l_I_V_41_fu_1125_p3 = ((icmp_ln443_11_reg_1593[0:0] == 1'b1) ? x_l_I_V_40_reg_1581 : p_Result_81_fu_1106_p5);

assign x_l_I_V_42_fu_1203_p3 = ((icmp_ln443_12_fu_1169_p2[0:0] == 1'b1) ? x_l_I_V_41_fu_1125_p3 : p_Result_84_fu_1181_p5);

assign x_l_I_V_43_fu_1282_p3 = ((icmp_ln443_13_reg_1616[0:0] == 1'b1) ? x_l_I_V_42_reg_1604 : p_Result_87_fu_1263_p5);

assign x_l_I_V_44_fu_1360_p3 = ((icmp_ln443_14_fu_1326_p2[0:0] == 1'b1) ? x_l_I_V_43_fu_1282_p3 : p_Result_90_fu_1338_p5);

assign x_l_I_V_45_fu_1421_p3 = ((icmp_ln443_15_fu_1391_p2[0:0] == 1'b1) ? x_l_I_V_44_reg_1627 : p_Result_93_fu_1401_p5);

assign x_l_I_V_fu_654_p3 = ((icmp_ln443_5_reg_1524[0:0] == 1'b1) ? x_l_I_V_35_reg_1512 : p_Result_63_fu_635_p5);

assign zext_ln443_10_fu_1090_p1 = tmp_2_fu_1072_p3;

assign zext_ln443_11_fu_1165_p1 = tmp_10_fu_1147_p3;

assign zext_ln443_12_fu_1247_p1 = tmp_11_fu_1229_p3;

assign zext_ln443_13_fu_1322_p1 = tmp_12_fu_1304_p3;

assign zext_ln443_14_fu_1387_p1 = tmp_13_fu_1380_p3;

assign zext_ln443_1_fu_380_p1 = tmp_3_fu_362_p3;

assign zext_ln443_2_fu_462_p1 = tmp_4_fu_444_p3;

assign zext_ln443_3_fu_537_p1 = tmp_5_fu_519_p3;

assign zext_ln443_4_fu_619_p1 = tmp_6_fu_601_p3;

assign zext_ln443_5_fu_694_p1 = tmp_7_fu_676_p3;

assign zext_ln443_6_fu_776_p1 = tmp_8_fu_758_p3;

assign zext_ln443_7_fu_851_p1 = tmp_9_fu_833_p3;

assign zext_ln443_8_fu_933_p1 = tmp_s_fu_915_p3;

assign zext_ln443_9_fu_1008_p1 = tmp_1_fu_990_p3;

assign zext_ln443_fu_296_p1 = tmp_fu_278_p3;

assign zext_ln594_fu_230_p1 = p_Result_48_fu_220_p4;

assign zext_ln666_fu_216_p1 = x_int_reg;

assign zext_ln671_fu_1443_p1 = mul_I_V_fu_1435_p3;

endmodule //eucDis_sqrt_fixed_33_33_s
